# Default values for your Helm chart
# This is a YAML-formatted file.

# Specify the image repository and tag
image:
  repository: spring-petclinic
  tag: latest
  pullPolicy: Never

# Specify the deployment settings
deployment:
  replicas: 1
  port: 8080
  # Add any additional deployment settings here

# Specify the service settings
service:
  type: ClusterIP
  port: 80
  # Add any additional service settings here

# Add any additional configurable parameters here