Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.ssh.forward_agent = true
  config.ssh.insert_key       = false
  config.vm.provision :shell, privileged: false do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/$USER/.ssh/authorized_keys
    SHELL
  end
 
  # Provisioning steps
  config.vm.provision "shell", inline: <<-SHELL
    # Update the package list
    sudo apt-get update

    # Install prerequisites for adding new repositories
    sudo apt-get install -y software-properties-common apt-transport-https wget

    # Add the deadsnakes PPA for installing the latest Python version
    sudo add-apt-repository ppa:deadsnakes/ppa
    sudo apt-get update
    sudo apt-get install -y python3.10 python3.10-venv python3.10-dev python3-pip

    # Set Python 3.10 as the default version of Python3
    sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1

    # Install VS Code
    wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
    sudo install -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/
    sudo sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
    sudo apt-get install -y apt-transport-https
    sudo apt-get update
    sudo apt-get install -y code

    # Clean up
    rm packages.microsoft.gpg
  SHELL

  # Optional: Configuring the virtual machine's resources
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"  # Set the memory for the VM
    vb.cpus = 2         # Set the number of CPUs for the VM
  end

  # Optional: Forwarding the port for SSH access
  config.vm.network "forwarded_port", guest: 22, host: 2222, auto_correct: true
  config.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
end